version: '3.8'

services:
  postgres:
    image: postgres:14.18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: examdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
